### ISSUE TITLE
MySQL fails sakila

### ISSUE THREAD

**Issue by valhuber** [valhuber/ApiLogicServer#1]
Use [sakila](https://github.com/LintangWisesa/Sakila_MySQL_Example)..

During ```.. ..Dynamic model import using sys.path: /Users/val/Desktop/create_api_logic_server/database```, get log:

```
Traceback (most recent call last):
  File "/Users/val/dev/ApiLogicServer/venv/lib/python3.9/site-packages/sqlalchemy/sql/schema.py", line 108, in _init_items
    spwd = item._set_parent_with_dispatch
AttributeError: 'function' object has no attribute '_set_parent_with_dispatch'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/val/dev/ApiLogicServer/app_logic_server/create_server.py", line 247, in find_meta_data
    importlib.import_module('models')
  File "/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/val/Desktop/create_api_logic_server/database/models.py", line 47, in <module>
    class Actor(SAFRSBase, Base):
  File "/Users/val/Desktop/create_api_logic_server/database/models.py", line 50, in Actor
    actor_id = Column(SMALLINT, primary_key=True)
  File "/Users/val/dev/ApiLogicServer/venv/lib/python3.9/site-packages/sqlalchemy/sql/schema.py", line 1464, in __init__
    self._init_items(*args)
  File "/Users/val/dev/ApiLogicServer/venv/lib/python3.9/site-packages/sqlalchemy/sql/schema.py", line 110, in _init_items
    util.raise_(
  File "/Users/val/dev/ApiLogicServer/venv/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
sqlalchemy.exc.ArgumentError: 'SchemaItem' object, such as a 'Column' or a 'Constraint' expected, got <function SMALLINT at 0x10fec1a60>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/val/dev/ApiLogicServer/app_logic_server/create_server.py", line 1109, in <module>
    main()
  File "/Users/val/dev/ApiLogicServer/venv/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/val/dev/ApiLogicServer/venv/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/val/dev/ApiLogicServer/venv/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/val/dev/ApiLogicServer/venv/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/val/dev/ApiLogicServer/venv/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/val/dev/ApiLogicServer/venv/lib/python3.9/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/val/dev/ApiLogicServer/app_logic_server/create_server.py", line 1032, in create
    api_logic_server(project_name=project_name, db_url=db_url,
  File "/Users/val/dev/ApiLogicServer/app_logic_server/create_server.py", line 911, in api_logic_server
    generate_from_model.generate_api_expose_and_ui_views()  # sets generate_from_model.result_apis & result_views
  File "/Users/val/dev/ApiLogicServer/app_logic_server/create_server.py", line 169, in generate_api_expose_and_ui_views
    metadata = self.find_meta_data(cwd, self.project_name, self.db_url)
  File "/Users/val/dev/ApiLogicServer/app_logic_server/create_server.py", line 252, in find_meta_data
    raise Exception("Unable to import models from:\n" +
Exception: Unable to import models from:
/Users/val/Desktop/create_api_logic_server/database, or/Users/val/dev/ApiLogicServer/app_logic_server, or
/Users/val/dev/ApiLogicServer/app_logic_server/app
```

and

**Comment by valhuber** [comment]
Fixed in 1.01.01.
