### ISSUE TITLE
Admin App loses context after cascade delete

### ISSUE THREAD

**Issue by valhuber** [valhuber/ApiLogicServer#30]
In the sample app, you can adjust the `Order` referential integrity options as [described here.](https://github.com/valhuber/ApiLogicServer/wiki#edit-modelspy-referential-integrity-eg-sqlite)  While this is properly handled by the api and logic, it causes a loss of context in the admin app:

```
Not found: Invalid "Customer" ID "ANTO"
Traceback (most recent call last):
 File "/Users/val/dev/safrs/safrs/safrs_api.py", line 613, in method_wrapper
   result = fun(*args, **kwargs)
 File "/Users/val/dev/safrs/safrs/jsonapi.py", line 259, in get
   instance = self.SAFRSObject.get_instance(id)
 File "/Users/val/dev/safrs/safrs/base.py", line 661, in get_instance
   raise NotFoundError(f'Invalid "{cls.__name__}" ID "{id}"')
safrs.errors.NotFoundError
NotFoundError Invalid "Customer" ID "ANTO"
```

**Comment by valhuber** [comment]
Fixed in ApiLogicServer 4.00.08
