### ISSUE TITLE
Bad model.py for SQL Server computed column

### ISSUE THREAD

**Issue by valhuber** [valhuber/ApiLogicServer#35]
Thanks for finding this, @AshleyJackson.

I have opened this new issue...

It looks like it has gone past that roadblock, but now this error has popped up.
```
.. .. ..Create resource_list - dynamic import database/models.py, inspect each class

===> ERROR - Dynamic model import failed in /home/ashley/api/api_logic_server/database - project run will fail
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/api_logic_server_cli/create_from_model/model_creation_services.py", line 705, in create_resource_list_from_safrs
    importlib.import_module('models')
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/ashley/api/api_logic_server/database/models.py", line 81
    s112 = Column(String(8, 'Latin1_General_BIN'), index=True, Computed('(CONVERT([char](8),[dt],(112)))', persisted=False))
                                                                                                                           ^
SyntaxError: positional argument follows keyword argument
.. .. ..Creation proceeding to enable manual database/models.py fixup
.. .. .. See https://github.com/valhuber/ApiLogicServer/wiki/Troubleshooting#manual-model-repair
 b.  Create api/expose_api_models.py from models
 c.  Create ui/admin/admin.yaml from models
.. .. ..Create ui/admin copy safrs-react-admin: /usr/local/lib/python3.9/dist-packages/api_logic_server_cli/create_from_model/safrs-react-admin-npm-build -> /home/ashley/api/api_logic_server/ui/safrs-react-admin
.. .. ..WARNING - no relationships detected - add them to your database or model
.. .. ..  See https://github.com/valhuber/LogicBank/wiki/Managing-Rules#database-design
.. .. ..Write /home/ashley/api/api_logic_server/ui/admin/admin.yaml
.. ..ui/basic_web_app creation declined
4. Final project fixup
 a.   Appending "from database import customize_models" to database/models.py
 b.   Update api_logic_server_run.py with project_name=api_logic_server and api_name, host, port
 c.   Fixing api/expose_services - port, host
 d.   Updated customize_api_py with port=5656 and host=localhost
 e.   Updated python_anywhere_wsgi.py with /home/ashley/api/api_logic_server

Run created ApiLogicServer project with command: python /home/ashley/api/api_logic_server/api_logic_server_run.py
app started: /home/ashley/api/api_logic_server/api_logic_server_run.py

Traceback (most recent call last):
  File "/home/ashley/api/api_logic_server/api_logic_server_run.py", line 51, in <module>
    from api import expose_api_models, customize_api
  File "/home/ashley/api/api_logic_server/api/expose_api_models.py", line 10, in <module>
    db_spec.loader.exec_module(models)
  File "/home/ashley/api/api_logic_server/database/models.py", line 81
    s112 = Column(String(8, 'Latin1_General_BIN'), index=True, Computed('(CONVERT([char](8),[dt],(112)))', persisted=False))
                                                                                                                           ^
SyntaxError: positional argument follows keyword argument
Traceback (most recent call last):
  File "/usr/local/bin/ApiLogicServer", line 8, in <module>
    sys.exit(start())
  File "/usr/local/lib/python3.9/dist-packages/api_logic_server_cli/cli.py", line 1445, in start
    main(obj={})
  File "/usr/lib/python3/dist-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/api_logic_server_cli/cli.py", line 1089, in create_and_run
    api_logic_server(project_name=project_name, db_url=db_url, api_name=api_name,
  File "/usr/local/lib/python3.9/dist-packages/api_logic_server_cli/cli.py", line 853, in api_logic_server
    create_utils.run_command(f'python {run_file}', msg="\nRun created ApiLogicServer project")
  File "/usr/local/lib/python3.9/dist-packages/api_logic_server_cli/create_from_model/api_logic_server_utils.py", line 77, in run_command
    result_b = subprocess.check_output(cmd, shell=True)  # , stderr=subprocess.STDOUT)  loses all logging
  File "/usr/lib/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'python /home/ashley/api/api_logic_server/api_logic_server_run.py' returned non-zero exit status 1.
```

I've run the same command as yesterday and I ran it without any parameteres.

```
root@ashley-ubuntu:/home/ashley/api# pip list | grep "ApiLogicServer"
ApiLogicServer          4.1.12
```

**Comment by valhuber** [comment]
Having trouble re-creating this; this test is working:

<img width="1482" alt="computed base col ok" src="https://user-images.githubusercontent.com/5579631/154316706-3b4576fe-6c4d-4481-a363-2a381bee65a9.png">

**Comment by AshleyJackson** [comment]
Hey mate.
Here's a self-destructing link for the models.py that gets generated.

https://pastebin.com/GjcLhW37

Is this enough for you?

**Comment by valhuber** [comment]
I did get it.  It's helpful - I can see that "-" is another character to test for (easy).

I do not see why line 81 fails, might be good to have DDL for that.

Did you understand that `use_model` for **Manual Model Repair** gives to a chance to correct these (e.g, replace `-` in names with `_`), and bypass issues temporarily (eg. comment out the Computed issue on line 81:
```
    s112 = Column(String(8, 'Latin1_General_BIN'), index=True, Computed('(CONVERT([char](8),[dt],(112)))', persisted=False))
```
